version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Подключаем вашу конфигурацию Nginx
      - ./:/app/public/assets
    ports:
      - "8083:80"
    depends_on:
      - web

networks:
  default:
    driver: bridge
